### ISSUE TITLE
Investigate failures

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits_backend#21]
## Description
Investigate what caused the failures (the system periodically accepts no more requests in scalability tests) and how they could be fixed/mitigated. Should we change something in the architecture, for example adding circuit breakers?

## Acceptance Criteria
- [ ] failures have been investigated

**Comment by PaulBredl** [comment]
Idk if anyone did anything here, but in my oppinion we might not need circuit breakers, because we don't have that much inner communication between the services. The reward and skill service do not completely crash when the other services are not available.

What we need to do is to make the gateway maybe more robust when a service is not available.
But this is also a frontend task: The frontend also needs robust error handling when a query returns an error and not completely crash.
